//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeTrack.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeTrack.Resources.Models.EditModel", typeof(EditModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Холодная вода.
        /// </summary>
        internal static string EditModel_ColdWater {
            get {
                return ResourceManager.GetString("EditModel_ColdWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение холодной воды должно быть больше либо равно указанному..
        /// </summary>
        internal static string EditModel_ColdWaterCondition {
            get {
                return ResourceManager.GetString("EditModel_ColdWaterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показания холодной воды должны быть заполнены..
        /// </summary>
        internal static string EditModel_ColdWaterRequired {
            get {
                return ResourceManager.GetString("EditModel_ColdWaterRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горячая вода.
        /// </summary>
        internal static string EditModel_HotWater {
            get {
                return ResourceManager.GetString("EditModel_HotWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение горячей воды должно быть больше либо равно указанному..
        /// </summary>
        internal static string EditModel_HotWaterCondition {
            get {
                return ResourceManager.GetString("EditModel_HotWaterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показания горячей воды должны быть заполнены..
        /// </summary>
        internal static string EditModel_HotWaterRequired {
            get {
                return ResourceManager.GetString("EditModel_HotWaterRequired", resourceCulture);
            }
        }
    }
}
